# Generated by Django 4.2.10 on 2024-03-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_agricola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='labels',
            field=models.FileField(upload_to='labels/'),
        ),
    ]
