# Generated by Django 4.2.10 on 2024-04-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_agricola', '0004_alter_imageupload_image_alter_imageupload_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='dpe',
            field=models.CharField(default='dpe', max_length=255),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='labels',
            field=models.FileField(upload_to=''),
        ),
    ]
