# Generated by Django 4.2.10 on 2024-04-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_agricola', '0005_alter_imageupload_dpe_alter_imageupload_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=50)),
                ('num_epoch', models.CharField(max_length=10)),
                ('fecha_train', models.DateTimeField(auto_now_add=True)),
                ('num_data', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('Untrained', 'Untrained'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpe', models.CharField(default='dpe', max_length=255)),
                ('images', models.ImageField(upload_to='')),
                ('labels', models.FileField(upload_to='')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('Untrained', 'Untrained'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AddField(
            model_name='datatrain',
            name='dpe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='datos_agricola.dataupload'),
        ),
    ]
