# Generated by Django 4.2.10 on 2024-04-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detection_dpe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('Untrained', 'Untrained'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
